@startuml
'https://plantuml.com/class-diagram

class BoardModel {
    -tasks : Task[]
    -repo : Repository

    __iter__() : BoardModelIterator
}

interface builtin.Iterable

class builtin.BoardModelIterator {
    model : BoardModel
}

builtin.Iterable  <|.. builtin.BoardModelIterator
builtin.BoardModelIterator --+ BoardModel

@enduml